### ISSUE TITLE
ansible-lint reports errors

### ISSUE THREAD

**Issue by vcrhonek** [linux-system-roles/timesync#31] opened 2019-04-10 10:20 UTC
See https://travis-ci.com/vcrhonek/timesync/builds/107422467

--> Executing Ansible Lint on /home/travis/build/vcrhonek/timesync/tests/tests_default.yml...
    [204] Lines should be no longer than 160 chars
    /home/travis/build/vcrhonek/timesync/tests/roles/linux-system-roles.timesync/tasks/main.yml:11
      when: timesync_mode is not defined and (timesync_ntp_servers|length == 0) and timesync_ptp_domains|length == 1 and timesync_ptp_domains[0].interfaces|length == 1
    
    [602] Don't compare to empty string
    /home/travis/build/vcrhonek/timesync/tests/roles/linux-system-roles.timesync/tasks/main.yml:20
      when: timesync_mode != 2 and (timesync_ntp_provider is not defined or timesync_ntp_provider == '')
    
    [602] Don't compare to empty string
    /home/travis/build/vcrhonek/timesync/tests/roles/linux-system-roles.timesync/tasks/main.yml:24
        timesync_ntp_provider: "{{ timesync_ntp_provider_os_default if timesync_ntp_provider_current == '' else timesync_ntp_provider_current }}"
    
    [602] Don't compare to empty string
    /home/travis/build/vcrhonek/timesync/tests/roles/linux-system-roles.timesync/tasks/main.yml:25
      when: timesync_mode != 2 and (timesync_ntp_provider is not defined or timesync_ntp_provider == '')

**Comment by pcahyna** [comment] 2019-05-10 10:10
re 602: probably related https://github.com/ansible/ansible-lint/issues/457

**Comment by richm** [comment] 2020-04-01 23:10
Is this still a problem?  Does https://github.com/linux-system-roles/timesync/pull/67 fix this?  If so, can we close this in favor of https://github.com/linux-system-roles/timesync/pull/67?

**Comment by richm** [comment] 2020-04-01 23:15
I don't see these errors: https://travis-ci.org/github/linux-system-roles/timesync/jobs/669508508?utm_medium=notification&utm_source=github_status
```
--> Executing Ansible Lint on /home/travis/build/linux-system-roles/timesync/tests/tests_default.yml...
Lint completed successfully.
```
Does this mean our template molecule based ansible-lint test isn't checking all of the ansible files?

**Comment by pcahyna** [comment] 2020-04-01 23:17
#67 does not do anything related. The issue is being avoided here. https://github.com/linux-system-roles/timesync/blob/488f359cb0ccade31fdf291b8487800c62d854ad/.ansible-lint#L3

Since this lint rule is just silly, I would say it is not a workaround, it is a real fix. Therefore, the issue can be closed.

**Comment by pcahyna** [comment] 2020-04-01 23:18
Oh and this .ansible-lint should be added to the template.

**Closed by pcahyna** 2020-04-01 23:17 UTC
