### ISSUE TITLE
timesync failes on fedora35 trying to disable ntpd service because it is not installed

### ISSUE THREAD

**Issue by RobVerduijn** [linux-system-roles/timesync#128] opened 2021-11-12 11:32 UTC
Hello,

When applying the timesync role on fedora35 it tries to disable ntpd and it failed because it is not installed.

somehow it failed to check that ntpd was not installed.

ansible and collections versions
```
ansible [core 2.12.0]
  config file = /home/rob/code/playbooks/ansible.cfg
  configured module search path = ['/home/rob/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rob/code/playbooks/venv/lib64/python3.10/site-packages/ansible
  ansible collection location = /home/rob/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/rob/code/playbooks/venv/bin/ansible
  python version = 3.10.0 (default, Oct  4 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
  jinja version = 3.0.2
  libyaml = True

ansible-galaxy collection list                                                                             127   master 

# /home/rob/.ansible/collections/ansible_collections
Collection                Version
------------------------- -------
RobVerduijn.lab           0.1.2  
ansible.netcommon         2.4.0  
ansible.posix             1.3.0  
ansible.utils             2.4.2  
ansible.windows           1.8.0  
community.crypto          2.0.0  
community.general         4.0.1  
community.libvirt         1.0.2  
community.windows         1.8.0  
fedora.linux_system_roles 1.10.1 
freeipa.ansible_freeipa   0.4.2  
theforeman.foreman        3.0.0  
theforeman.operations     0.3.0

```

**Comment by spetrosi** [comment] 2021-11-12 11:40
Hello, please share the playbook that you used so that we can reproduce the issue

**Comment by RobVerduijn** [comment] 2021-11-12 11:44
reproducer:
```
---
- name: reproducer
  hosts: poc.linux.lab
  gather_facts: true
  remote_user: root

  tasks:
    - name: include role
      include_role:
        name: fedora.linux_system_roles.timesync
```
see the attachement for the logs
[output.txt](https://github.com/linux-system-roles/timesync/files/7527311/output.txt)

**Comment by spetrosi** [comment] 2021-11-12 12:23
I am trying to reproduce this and in my tests Ansible skips the task `Disable ntpd`. What variables do you pass with the role?

**Comment by RobVerduijn** [comment] 2021-11-12 13:01
Hello,

I've run the play again now with debug statement at the beginning and  end 

see the attachment for results

```
- name: reproducer
  hosts: poc.linux.lab
  gather_facts: true
  remote_user: root

  tasks:
  - name: debug hostvars before failure
    debug:
      var: hostvars

  - block:
    - name: include role
      include_role:
        name: fedora.linux_system_roles.timesync
    
    rescue:
      - name: debug hostvars after failure
        debug:
          var: hostvars
```
[hostvars.txt](https://github.com/linux-system-roles/timesync/files/7527692/hostvars.txt)

**Comment by spetrosi** [comment] 2021-11-12 13:40
From your output.txt I see that the system has some services with the status `not-found`. The ones that are related to the timesync role are  `sntp`, `ntpd`, ntpdate`.
I do not know how they could have such status, and cannot reproduce it neither. I wonder they were installed and then removed, but the services kept hanging with the `not-found` status.

**Comment by RobVerduijn** [comment] 2021-11-12 14:20
I'm using a custim image which is a very minimal install of fedora35.
However I did not install and remove ntp.

For the kickstart that I used to create the image see https://github.com/RobVerduijn/lab/blob/master/roles/create_cfg_iso/templates/Fedora35-ks.cfg.j2

The only thing I can think of is that virt_sysprep set something in the image when I used it to seal it.

**Comment by spetrosi** [comment] 2021-11-12 14:43
You can work around this by filtering out services with the `not-found` status. Try editting `~/.ansible/collections/ansible_collections/fedora/linux_system_roles/roles/timesync/tasks/main.yml`. In this file, edit the `- name: Set variable `timesync_services` with filtered uniq service names` tasks as follows:

```
- name: Set variable `timesync_services` with filtered uniq service names
  set_fact:
    timesync_services: "{{ ansible_facts.services.values() | selectattr('name', 'defined') | selectattr('status', '!=', 'not-found') | map(attribute='name') | map('regex_replace', '[.]service.*$', '') | map('regex_replace', '@$', '') | unique | list }}"
```

I've added `selectattr('status', '!=', 'not-found')` after the first `selectattr` filter to the original task.

**Comment by RobVerduijn** [comment] 2021-11-12 14:59
that work for me
the Timesync role finishes now with errors

thanx

**Comment by RobVerduijn** [comment] 2021-11-12 14:59
that work for me
the Timesync role finishes now with errors

thanx

**Comment by spetrosi** [comment] 2021-11-12 15:44
@mlichvar do you think it's find to add such a workaround to the role itself? This weird `not-found` service status sounds to me like a Fedora bug honestly.

**Comment by mlichvar** [comment] 2021-11-15 13:26
In the ansible_facts code I see a change which might fix this issue:

https://github.com/ansible/ansible/pull/75326

This doesn't seem to be in Fedora yet.

**Comment by RobVerduijn** [comment] 2021-11-17 07:49
I found this issue while running ansible core 2.12.0 in a venv on fedora.
So it seems that it isn't in ansible-core 2.12.0 as well

**Comment by richm** [comment] 2021-11-18 00:56
fixed by https://github.com/linux-system-roles/timesync/pull/129

**Closed by richm** 2021-11-18 00:56 UTC
